# Generated by Django 5.2.6 on 2025-09-15 12:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_email_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
