# Generated by Django 5.2.6 on 2025-09-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_alter_email_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
